### ISSUE TITLE
Sandbox test not working 

### ISSUE THREAD

**Issue by jasenkabalac** [AndyMcKenna/NopCommerce_FirstData#2]
I am trying to test this plugin. I created a free test account and did all configuration steps. Then I filled in test card on my website - Visa 4111111111111111 and in the next step there is an error that says Nullable object must have a value.

System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at BitShift.Plugin.Payments.FirstData.FirstDataPaymentProcessor.ProcessPayment(ProcessPaymentRequest processPaymentRequest)
   at Nop.Services.Payments.PaymentService.ProcessPayment(ProcessPaymentRequest processPaymentRequest) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Payments\PaymentService.cs:line 77
   at Nop.Services.Orders.OrderProcessingService.GetProcessPaymentResult(ProcessPaymentRequest processPaymentRequest, PlaceOrderContainer details) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1425
   at Nop.Services.Orders.OrderProcessingService.PlaceOrder(ProcessPaymentRequest processPaymentRequest) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1572

**Comment by AndyMcKenna** [comment]
What version of Nop are you using?

I'm suspicious of these lines:
`var billingState = _stateProvinceService.GetStateProvinceById(billingAddress.StateProvinceId.Value);  `
`var billingCountry = _countryService.GetCountryById(billingAddress.CountryId.Value);`

Does your billing address have a state and country?

**Comment by jasenkabalac** [comment]
Thank you, yes, we are from Serbia and we don't have states so that was one
of the problems.
Our bank gave us data in the table below so is there a way we can use them
with your plugin, because we don't have any other information. I am using
Nop 4.30.


суб, 3. окт 2020. у 15:28 Andy McKenna <notifications@github.com> је
написао/ла:

**Comment by AndyMcKenna** [comment]
FYI I edited your comment to remove what looked like sensitive information.

**Comment by AndyMcKenna** [comment]
This is now fixed in version 4.3.14.  I tested with a Serbian address and verified the transaction worked in my local version of Nop and was in my demo FirstData portal.
